#pragma once
#include <cctype>
#include <codecvt>
#include <cwctype>
#include <cmath>
#include <fstream>
#include <iostream>
#include <iterator>
#include <map>
#include <set>
#include <string>
#include <tuple>
#include <vector>
#include <Windows.h>

using std::cerr;
using std::cout;
using std::endl;
using std::get;
using std::ifstream;
using std::locale;
using std::map;
using std::set;
using std::string;
using std::to_string;
using std::tuple;
using std::vector;
using std::wofstream;
using std::wstring;