#include <algorithm>
#include <fstream>
#include <iostream>
#include <locale>
#include <set>
#include <string>
#include <tuple>
#include <vector>

using std::cout;
using std::endl;
using std::ifstream;
using std::locale;
using std::set;
using std::string;
using std::to_string;
using std::tuple;
using std::vector;
using std::wstring;